### ISSUE TITLE
Problem in training

### ISSUE THREAD

**Issue by wuyuebupt** [fmcp/EndToEndIncrementalLearning#3]
After running the first incremental step on cifar for 40 epochs, I met two bugs and provide my temporal solution below. @fmcp will you be able to help take a look? Appreciate that. 

1. 
```
Undefined function or variable 'build_examplars_set'.

Error in incremental_training (line 163)
exemplars = build_examplars_set(lastExemplars, imdb_or, opts);

Error in experiment_cifar (line 93)
                [net, info, meta, exemplars] = incremental_training(net, imdb, exemplars, opts);
```

This seems to be a typo in the function name between "build_examplars_set" and "build_exemplars_set". I just simply copy the script "build_exemplars_set.m" to "build_examplars_set.m" and change the function name. I leave the "incremental_training.m" unchanged. 

2. 
```
Reference to non-existent field 'orig_loss'.

Error in fork_resnet_distillation (line 16)
if strcmp(opts.orig_loss, 'for_keep')

Error in incremental_training (line 265)
[net, derOutputs] = fork_resnet_distillation(net, ...

Error in experiment_cifar (line 93)
                [net, info, meta, exemplars] = incremental_training(net, imdb, exemplars, opts);
```
This seems that the "opts.orig_loss" is not defined. So the solution is to add one line before the if condition, e.g. `opts.orig_loss= 'for_keep';`

Now it seems that the codes are running with the balance fine-tuning with 30 epochs. Waiting for the results.

**Comment by wuyuebupt** [comment]
Get another error after 70 epochs. Start wondering if the opts is a global variable.
```
Undefined variable "opts" or class "opts.orig_loss".

Error in fork_resnet_remove_distillation (line 4)
if strcmp(opts.orig_loss, 'for_keep')

Error in incremental_training (line 295)
[net, derOutputs] = fork_resnet_remove_distillation(net);

Error in experiment_cifar (line 93)
                [net, info, meta, exemplars] = incremental_training(net, imdb, exemplars, opts);
```

**Comment by wuyuebupt** [comment]
I think I might succeed to run the training codes. 

Working on the testing code now. 
```
Reference to non-existent field 'eqlabs'.

Error in test_cifar (line 69)
                        estim_labels_(nscore_idx) = net.meta.eqlabs(index);
```
`eqlabs` is not defined in the `net.meta`.

**Comment by fmcp** [comment]
Thanks for the solutions! I forgot some changes in the last commit. I updated the code to solve the problems.

Regarding the `eqlabs`, it is included in the `net` variable in `incremental_training.m`. 

Are you using the final model during testing?

**Comment by fmcp** [comment]
I made some changes to fix that problems. Basically, I forgot that I made some changes in the ResNet library to deal with the smaller number of classes. Now the code should work without problems. 

In your case, you have to change the ResNet library to train the exact number of classes (by default it builds a classifier with 100 classes). I think that's your problem. Don't forget to remove all previous models and start from scratch.
